name: deploy-client

on:
  push:
    branches:
      - master
    paths:
      - "client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd client && docker build -t mofasa101/client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push mofasa101/client
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/aks-set-context@v1
        with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
           resource-group: 'blah'
           cluster-name: 'ticketing-dev'
      - run: kubectl rollout restart deployment client-depl
