name: deploy-auth

on:
  push:
    branches:
      - master
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd auth && docker build -t mofasa101/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push mofasa101/auth
      - uses: azure/login@v1
        with:
           creds: ${{ secrets.AZURE_CRED }}
      - uses: azure/aks-set-context@v2
        with:
           resource-group: "blah"
           cluster-name: "ticketing-dev"
      - run: kubectl rollout restart deployment auth-depl
